### ISSUE TITLE
PkgTestSuite has build errors

### ISSUE THREAD

**Issue by maikkirapo** [JuliaFEM/PkgTestSuite.jl#1]
Following error appears while cloning the package from Git Hub and trying to use it.

![asdfh](https://user-images.githubusercontent.com/28561253/28574598-1b7d079a-7157-11e7-9682-8a3c97394c1b.PNG)

**Comment by ahojukka5** [comment]
Looks that problem is somewhere else than in PkgTestSuite. Problem is with git.
